### ISSUE TITLE
Add UI Languages,  Schedules Log, and Log Browsing

### ISSUE THREAD

**Issue by adewararilwan** [z3r0c00l-2k/AquaDroid#12]
#### Component
My Suggestion is on the: 
- Setting Interface

## Proposal
> AquaDroid is an application which is based on reminder and tracking, it reminds the user to drink water and the same time track the user water intake habit.

Adding the new feature will improve the application
- UI Language
- Graphic/ Log schedule
- Log browsing  

#### UI Language –
 I suggest the addition of UI language to the application. The application is a worldwide application and there are always some cases whereby the user might not be a native English speaker and might not even be able to read and write the English Language. 
Currently, the application is written and programmed using the English language. The addition of UI language will allow the user to change to the language of choice for proper understanding and usage.  

#### Schedules Log -
 I suggest the addition of schedules log that will give the user the privilege of a pictorial view of the statistical history of water consumption daily, monthly and yearly. 

#### Log Browsing- 
I suggest the addition of Log browsing.  This also functions as a form of “search” where users can be able to search and find a particular schedule by date, month and year in case of future use.

# <center>MOCKUP EXAMPLES</center>
![Languagge UI.jpg](https://cdn.steemitimages.com/DQmejCrufAybuUDU1mAWG4duFGULj6Ay1DnzvRzWTLKnqxg/Languagge%20UI.jpg)
The image above shows how the UI Language feature will look like when implemented that will allow users to be able to change to the language of choice.

![Schedule Log.jpg](https://cdn.steemitimages.com/DQmUadNVY5L6sNtFi6mHiyEdg1hKYeASqy3BEPyfs1DTQEM/Schedule%20Log.jpg)
The image above shows how the schedule log feature will look like when implemented that will allow users to be able to view their water intake record daily, monthly and yearly.

![Log Browsing.jpg](https://cdn.steemitimages.com/DQmUHtmsKPvt7RE1iM9ABVMsayMX8MXRZ6V7kuxakErbpZn/Log%20Browsing.jpg)
The image above shows how the log browsing feature will look like when implemented that will allow users to be able to search for scheduled daily, monthly and yearly for future use.

### Benefits
If the proposed features are implemented, they will create greater benefits to the users. These benefits are:

 ### *UI Language –* 
This will be a very important feature that will improve the application.  Changing of language by users should be enabled that will allow users that do not understand how to read and write the English language to change to the language of their choice.  Users changing to the preferred language will help them in having a clearer understanding of the application function and simple usage with no difficulty.

### *Schedules Log –* 
This will be a very important feature that will improve the application. Since the users are able to view their water consumption record daily, monthly and yearly. It will be a driven force on the user’s effort either to improve their drinking habit or any other way around. All schedules of users based on water consumption will be noted on the log interface.

#### *Log Browsing-* 
This will be a very important feature that will improve the application. This feature, when implemented, will allow the user to be able to search for the schedule on the log using the simple search/browsing box. In the situation where records are kept in the log for a long period of time and it will take a lot of time before scrolling down to the main schedule user is looking for, with this feature the user just need to insert the date and month schedule is been open, then the schedule will appear with no time wasted.

## Conclusion
The AquaDroid application will gain increased adoption if the proposed features are implemented. It will definitely improve the user's experience and improve the application as a whole.

# MY GITHUB PROFILE 
https://github.com/adewararilwan

**Comment by z3r0c00l-2k** [comment]
@adewararilwan  If you are interested in contributing, please fork my repo and send a pull request for your changes

**Comment by mondstern** [comment]
I'm also interested in translating the app.
