### ISSUE TITLE
Back button wipes profile

### ISSUE THREAD

**Issue by whiskeyalfaone** [z3r0c00l-2k/AquaDroid#2]
After I first booted the app, I input all my information.  I then added my water information for the day (so far).  Upon accidentally pressing the back button, I was sent back and had to re-input all of my personal details (weight, gender, etc) because they were wiped.  While not a major issue, it was still a pain.

**Comment by z3r0c00l-2k** [comment]
I think its a normal behavior, right? @whiskeyalfaone

**Comment by whiskeyalfaone** [comment]
When somebody has already setup an app, it would be abnormal for the back button to wipe the information.  In some apps a user may be reverted to the previous screen, but the previously entered information would be pre-populated into the fields.

**Comment by z3r0c00l-2k** [comment]
Normally if you clicked continue , the data will be stored and u will get to home screen. 
The back button closes the app, it destroy the activity and the data in the text fields... 
So to solve this issue may be i can add a double back press to exit.... What your opinion?? @whiskeyalfaone
