### ISSUE TITLE
App gets creshed when I open  the settings and rotate my phone.

### ISSUE THREAD

**Issue by pzdawood** [z3r0c00l-2k/AquaDroid#20]
***Describe the bug***
When I open the app and tries to change my settings and rotate phone to any direction either portate mode or landscape mode app gets creshed.
***To produce***
1. Open the aquaDroid app.
2. Open settings.
3. Rotate your phone in any mode.
3. App gets creshed.
***Expected behaviour***
When I open the settings and rotate my phone app must withstand and settings must appear in any mode.
Devices and Versions
Device: Redmi 4
Version :7.1.2
App version :1.2

***Recording of the bug***
https://youtu.be/T0ig375ZTeg

**Comment by z3r0c00l-2k** [comment]
This issue fied in commit [b480cda](https://github.com/z3r0c00l-2k/AquaDroid/commit/b480cdaed0d347a5596621c9464819e562081e5b)
