### ISSUE TITLE
App did not work properly in landscape mode .

### ISSUE THREAD

**Issue by pzdawood** [z3r0c00l-2k/AquaDroid#21]
***Description of bug***
When I open the app in landscape mode all the intake options gets disable andare unseen so we can't take intake in landscape mode also some settings can not seen in landscape mode.
***How to reproduce***
1. Open the aquaDroid app in landscape mode or open app and then rotate it in landscape mode.
2. The intake options gets unseen.
4. Open the settings.
5. Some settings can't be changed.
***Expected behaviour***
When I open the app in landscape mode or rotate it to landscape mode all intake options must be see and app must work Normally. Also all settings must be changeable.
***Recording of bug***
https://youtu.be/-opPUDpWHsc
Device: Redmi 4
Version :7.1.2
App version :1.2

**Comment by z3r0c00l-2k** [comment]
This issue fied in commit [b480cda](https://github.com/z3r0c00l-2k/AquaDroid/commit/b480cdaed0d347a5596621c9464819e562081e5b)
