### ISSUE TITLE
330ml and custom quantity

### ISSUE THREAD

**Issue by beng7** [z3r0c00l-2k/AquaDroid#23]
Hi
Please provide 330ml quantity, which is the standard quantity of a can + provide an option for the user to define and record their custom quantity along with drop down list to define beverage: aqua, soft... 
Beer/alcohol not included in your options/ algorithms (dehydration effect)?
Thanks
(Phone=H930DS, lineage 16 (android 9))

**Comment by z3r0c00l-2k** [comment]
@beng7 please check this [relese](https://github.com/z3r0c00l-2k/AquaDroid/releases/tag/v1.3)
