### ISSUE TITLE
New version of aquadroid on fdroid

### ISSUE THREAD

**Issue by paulle** [z3r0c00l-2k/AquaDroid#28]
The new version of aquadroid will be on f-droid?
Till now the new version is not on f-droid. It would be nice to see it there.
Thank you

**Comment by z3r0c00l-2k** [comment]
I have talked with the F-Droid team regarding this issue. They had a networking issue recently, so lot apps building got failed and it is in the building queue. It will take at least 3 weeks from now to see in F-Droid repo
