### ISSUE TITLE
Settings page typos and display issues

### ISSUE THREAD

**Issue by whiskeyalfaone** [z3r0c00l-2k/AquaDroid#3]
'You daily work time in min/day' should be 'Your daily work time in min/day'
'Notification messgae' should be 'Notification message'

The time selections under the notification settings do not display well.  I have a Samsung Galaxy S5.  I cannot read all the text for '60 minutes' because the 6 is cut off.  It seems that the font is larger on that button.  The '45 minutes' barely fits.  Perhaps abbreviating 'minutes' to 'mins' would fix the issue.

The icon on the 30 minutes button is on the left, but on the others, it is on the right.  For consistency's sake, it would be better if they were all on the same side.  In my opinion, left looks better.

I also think it would be more logical if 'sleep time' was on the left and 'wake time' was on the right because you go to sleep before you wake up.  At least that's what makes sense to me.

**Comment by whiskeyalfaone** [comment]
I should add, I really like your app.  Please do not take offence to me nit-picking, I do it professionally so I cannot help it.

**Comment by MinIsMin** [comment]
Screenshot showing the visual minutes differences
![grafik](https://user-images.githubusercontent.com/18466226/59091064-05aff880-88fe-11e9-8931-10b5ef54ccf3.png)

**Comment by whiskeyalfaone** [comment]
And mine
![Screenshot_20190607-201733_AquaDroid](https://user-images.githubusercontent.com/44386354/59097735-aaafed00-8961-11e9-9612-fd8382016b9e.png)

**Comment by z3r0c00l-2k** [comment]
I think i should use "mins" instead of "minutes"...

**Comment by MinIsMin** [comment]
I just add this here:

![grafik](https://user-images.githubusercontent.com/18466226/59121051-91e60e00-8946-11e9-8c27-d00d74808764.png)

```
for you...!!
Wake up time
```

the visual minutes seems fixed now

version 1.2

**Comment by whiskeyalfaone** [comment]
I think the font size on the '30 mins' is bigger but it all shows up and can be read now.
![Screenshot_20190608-174617_AquaDroid_1](https://user-images.githubusercontent.com/44386354/59144090-a6450c00-8a15-11e9-8f47-aab87624e231.png)

**Comment by z3r0c00l-2k** [comment]
Selected option is set to be bigger...
