### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by paulle** [z3r0c00l-2k/AquaDroid#30]
I like your app, so I did a translation of the string file into German: Maybe you can include it.
[strings-de.txt](https://github.com/z3r0c00l-2k/AquaDroid/files/4139182/strings-de.txt)

**Comment by z3r0c00l-2k** [comment]
Please send me a pull request...

**Comment by paulle** [comment]
Don't know how to do  it, because I know nothing about coding. Sop I do only reporting Bugs or translations. Excuse me. Sorry.

**Comment by mondlicht-und-sterne** [comment]
@z3r0c00l-2k you should be able to see something now with "add german translation". i put the name of the person who translated it there. i hope the app will be available in german soon.
