### ISSUE TITLE
Wrong label name in settings for one of the time fields

### ISSUE THREAD

**Issue by uli-on** [z3r0c00l-2k/AquaDroid#34]
The "Your wake up time" label exists twice in Settings, which makes it a guesswork to correct any of those fields.

Android 6.0.1
Moto G4
App v1.3 from F-Droid

**Comment by paulle** [comment]
Here too.
android 10
v1.3 from F-Droid

**Comment by LongJohn-Silver** [comment]
Same here, Samsung J4, Android 10, v1.3 from F-Droid.
