### ISSUE TITLE
Mistake in German app description

### ISSUE THREAD

**Issue by ksaerdna** [z3r0c00l-2k/AquaDroid#35]
This one:

**AquaDroid erinnert dich daran, Wasser zu trinken und zeichnet dein Trinkverhalten auf.**

must be like that:

**AquaDroid erinnert dich daran, Wasser zu trinken, und zeichnet dein Trinkverhalten auf.**

Note the missing comma. To be precise: "Wasser zu trinken" is the sentence segment which must be **enclosed** in commas. This is a widespread mistake which was additionally encouraged when the German government sabotaged punctuation and orthography in 1996 due to political reasons.

**Comment by z3r0c00l-2k** [comment]
Please send a pull request with this fix
