### ISSUE TITLE
Feature request - Editable 'favourite' buttons instead of predefined

### ISSUE THREAD

**Issue by whiskeyalfaone** [z3r0c00l-2k/AquaDroid#4]
I would like to be able to edit the six buttons on the main screen.  I do not drink any of the bottom three items so it would be more useful if I could change them.

For example, I drink a full 750ml bottle of water when I wake up.  I could create a 750ml water button instead of milk.

My standard glass (of water) is 500ml, but I occasionally have 300ml ones. Instead of 200ml (that is already there) I would change that to 250ml and create a 300ml one instead of soft drink or something.  At present, I mark 400ml for every first glass and 600ml for every second glass, but it is annoying having to remember when I drank what.  After all, the whole point of the app is not having to remember, right?

It also seems to me like it would be better if the sixth button was an 'other' button that prompted the user to enter a different amount from what is on the other five buttons. It could ask for the amount and the type of liquid.

**Comment by z3r0c00l-2k** [comment]
@whiskeyalfaone Fork and do the change as you need......😉😉😉😉
