### ISSUE TITLE
Feature request - clicking the notification opens the app

### ISSUE THREAD

**Issue by whiskeyalfaone** [z3r0c00l-2k/AquaDroid#5]
When I click the notification, it does not do anything.  It makes sense to me that clicking it should open the app.

I am on Android 9 (Llama?) if that makes a difference.

**Comment by z3r0c00l-2k** [comment]
@whiskeyalfaone   I already added that.. i don't know why its not working on Pie . will look into it...😀😀

**Comment by z3r0c00l-2k** [comment]
@whiskeyalfaone   I already added that.. i don't know why its not working on Pie . will look into it...👍👍👍👍

**Comment by z3r0c00l-2k** [comment]
@whiskeyalfaone please check the latest release..
[v1.2](https://github.com/z3r0c00l-2k/AquaDroid/releases/tag/v1.2)

**Comment by whiskeyalfaone** [comment]
Yep.  It now works as expected.  Thank you.
