### ISSUE TITLE
Walkthrough cut off text

### ISSUE THREAD

**Issue by MinIsMin** [z3r0c00l-2k/AquaDroid#6]
The text in the walkthrough is cut off

**Device**: Samsung Galaxy Express - 800x480 (~207 ppi)

![1](https://user-images.githubusercontent.com/18466226/59091564-24fb5580-88ff-11e9-8832-66294463fabd.jpg)
![2](https://user-images.githubusercontent.com/18466226/59091565-24fb5580-88ff-11e9-808b-f2f5af32af4d.jpg)
![3](https://user-images.githubusercontent.com/18466226/59091566-24fb5580-88ff-11e9-943f-0e6ddd6fe191.jpg)

**Comment by z3r0c00l-2k** [comment]
Thank you for the report ... i will fix it in this weekend..👍

**Comment by z3r0c00l-2k** [comment]
@MinIsMin please check the latest release..
[v1.2](https://github.com/z3r0c00l-2k/AquaDroid/releases/tag/v1.2)

**Comment by MinIsMin** [comment]
Looks good now.
