### ISSUE TITLE
Copycat/clone of AquaDroid on Google Play

### ISSUE THREAD

**Issue by Poussinou** [z3r0c00l-2k/AquaDroid#67]
Hi @z3r0c00l-2k 

I found this app on the Google Play Store: https://play.google.com/store/apps/details?id=ge.georgiandev.waterreminder from [this developer](https://play.google.com/store/apps/developer?id=GeorgianDev). This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, you can follow [that procedure](https://gist.github.com/Poussinou/86136151f8b939fbaa48650666bf62d6) to remove this copy from the Store, if it's your wish.

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by username-is-not** [comment]
![Screenshot_2024-03-02-01-46-11-898_org mozilla fennec_fdroid](https://github.com/z3r0c00l-2k/AquaDroid/assets/80984663/c9eeea91-766e-41b1-addf-51c8275c67ba)

... Is it not letting ME report it, or?

**Comment by Poussinou** [comment]
Everything was taken down, please report any other copycat here in the future
